---
- name: Install dependencies for OctoPrint.
  package:
    name: '{{ octoprint_dependencies }}'
    state: latest

- name: Create OctoPrint user.
  user:
    name: '{{ octoprint_user }}'
    append: yes
    groups: dialout,tty,staff

- name: Clean all allowed OctoPrint user 'sudo' commands.
  lineinfile:
    state: absent
    path: /etc/sudoers
    regexp: '^{{ octoprint_user }}'
    validate: 'visudo -cf %s'

- name: Allow OctoPrint user to execute defined 'sudo' commands.
  lineinfile:
    path: /etc/sudoers
    regexp: '^{{ octoprint_user }} ALL=(ALL) NOPASSWD: {{ item.value | regex_replace("^sudo ") }}$'
    line: '{{ octoprint_user }} ALL=(ALL) NOPASSWD: {{ item.value | regex_replace("^sudo ") }}'
    validate: 'visudo -cf %s'
  with_items: '{{ octoprint_config_server_commands | dict2items }}'
  when: item.value | regex_search("^sudo ")

- name: Create octoprint config dir.
  file:
    path: '/home/{{ octoprint_user }}/.octoprint'
    state: directory
    owner: '{{ octoprint_user }}'

# Avoid config suppression on upgrade
- name: Octoprint config exist?
  stat:
    path: '/home/{{ octoprint_user }}/.octoprint/config.yaml'
  ignore_errors: true
  register: octoprint_config

- name: Install octoprint config.
  template:
    src: octoprint.config.j2
    dest: '/home/{{ octoprint_user }}/.octoprint/config.yaml'
    owner: '{{ octoprint_user }}'
    group: '{{ octoprint_group }}'
  when: octoprint_config.stat.exists == false

- name: Clone Octoprint release.
  register: octocloned
  git:
    repo: '{{ octoprint_repo }}'
    dest: '{{ octoprint_install_dir }}'
    version: '{{ octoprint_version }}'
    depth: 1

- name: Set ownership of octoprint install octoprint_install_dir.
  file:
    path: '{{ octoprint_install_dir }}'
    recurse: yes
    owner: '{{ octoprint_user }}'

- name: Setup OctoPrint.
  when: octocloned.changed
  shell: python3 setup.py install
  args:
    chdir: '{{  octoprint_install_dir  }}'

- name: Set ownership of octoprint deamon.
  file:
    path: /usr/local/bin/octoprint
    owner: '{{ octoprint_user }}'

- name: Setup Octorpint systemd service.
  template:
    src: octoprint.service.j2
    dest: /lib/systemd/system/octoprint.service
  notify: Start Octoprint
